baseURL = "https://blog.zshipu.com/"
languageCode = "zh-CN"
title = "知识铺的博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "知识铺"

[params]
  author = "知识铺"
  subtitle = "专注于Android、Java、Go语言(golang)、移动互联网、项目管理、软件架构"
  keywords = "golang,go语言,go语言笔记,知识铺,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "知识铺,一个知识分享，积累，整理的地方。"
  busuanzi = true #启用不算子网页统计
  googleAd = "ca-pub-2874221941555456"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "浙 ICP 备19032823号-1"

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "知识铺的博客"
  name = "知识铺的博客"
  url = "https://blog.zshipu.com//"


## 侧边栏广告位
[[params.ads]]
  title = "【2019双12】ALL IN CLoud 低至1折"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?source=5176.11533457&userCode=tzm8r4hc"
  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"
[[params.ads]]
  title = "助力产业智慧升级，云服务器首年88元起，更有千元代金券礼包免费领！"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?source=5176.11533457&userCode=tzm8r4hc"
  img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
[[params.ads]]
  title = "【渠道专享低折扣】11月特惠 限时2折"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?source=5176.11533457&userCode=tzm8r4hc"
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "https://github.com/liliang8858/zspblogcomment" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]


  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
